[package]
name = "pvpn"
version = "0.1.0"
edition = "2024"

[dependencies]
bincode = "2.0.1"
chrono = "0.4.42"
clap = { version = "4.5.48", features = ["derive"] }
derive_more = { version = "2.0.1", features = ["from"] }
fern = "0.7.1"
futures = "0.3.31"
hexdump = "0.1.2"
log = "0.4.28"
mio = "1.0.4"
rstaples = "0.1.3"
tokio = { version = "1.47.1", features = ["io-util", "macros", "net", "rt-multi-thread", "sync", "time"] }

[profile.release]
strip = true    # Automatically strip symbols from the binary.
opt-level = "s" # Optimize for speed
lto = true
