[package]
name = "tunnel"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "client"
path = "src/bin/client/client.rs"

[[bin]]
name = "server"
path = "src/bin/server/server.rs"

[dependencies]
bincode = "2.0.1"
chrono = "0.4.40"
clap = { version = "4.5.34", features = ["derive"] }
derive_more = { version = "2.0.1", features = ["from"] }
fern = "0.7.1"
log = "0.4.27"
tokio = { version = "1.44.1", features = ["macros", "net", "rt-multi-thread"] }
