[package]
name = "pvpn"
version = "0.1.0"
edition = "2024"

[dependencies]
bincode = "2.0.1"
chrono = "0.4.40"
clap = { version = "4.5.35", features = ["derive"] }
derive_more = { version = "2.0.1", features = ["from"] }
fern = "0.7.1"
hex = "0.4.3"
log = "0.4.27"
tokio = { version = "1.44.2", features = ["io-util", "macros", "net", "rt-multi-thread", "sync", "time"] }

[profile.release]
strip = true    # Automatically strip symbols from the binary.
opt-level = "s" # Optimize for speed
lto = true
